sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
jdk: oraclejdk8
script:
- bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: s63DlgXhOE2g5nfKbAsgYOn/BsJ8Rrln8s0UBajc2UvSb2kgCkfLojNyhWprl9kqkSDKVDv8p0IakZNpGV4iW1N2h7Ci9hwOoyoI0GG1nzUvPZehNkawh5dcoUneG15HQ6t5qMBzVeBsxkZO5ifKvHesZ+WIda0JcPcTumiZb11iNhXMYbAryHu7n193SvR4AKFZHgAAlLr+2biQDdAj78yGug5KxJIwpdFgTv5SInnYZ6bOX/0dLXOhqEJchcTk1D5GZNi8nEqQQNO9C2HPxm4vkbtVpGl/8EWANHyoWn6cvAs3ZU6YA6vduBByoAL8V8YYVlKCvHrlv7QoOTzbpvxKN9XKC17gvuGXIlL1YD/WY9csIRd2jvOXdAiwTtZ0FpeocYoJQwRkvk3z4KaMHPy7IPBWkj/lmqQOHbhdu1bZ8GlV348y+H/zW2a0x1Xeylorkx8++CL6SuMhP2He7x1K/X7+64iKqmLs1X2eoLh5U9rmsbQ2IC2MZn1XFVaEBA2/zGM3GMCVAVbrZq627NeU6kI2hi9y9b7ZkcKaSsO9wLeUR2hnMdJeLaEgqvgzGY3NDdPztUWXj+nZgch4i9JFYkIoGuVo8V87d0aLypaX+iWdrcapa+zFcBkwFso1BSMUJIYPpHTUOZqKJWCbu+UrBiOiZQFJSxCjwX/t0kY=
  on:
    tags: true
  gem: logstash-filter-cache-redis
