sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
jdk: oraclejdk8
script:
- bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: EH2Iyk/z8bBBHM0mXHgWWSGntJ6vjOnWrhITRr6ja6A00olL3Lba9pzTWclJ/LOTZAQOWTfJmdFAjrvtFwIRd8Pg5t97MDPSmGiERivyfHT9dUK+2G1DlmTjZy2RR3f/uPrpeJV1I0KqVEPBsJVdoWhmP5Xvh3FNIm1H/SgK+Xs0Eo9G8VEyZKS3jfEdPthNYs0tgPEbQyGE+IbT0G0d7UNe5O7WeLNf49qTovvqlVJDUipQIwOYHYF3BBqk8l5St0YkxJC0ULg3NPctrppl4hz3t/c/JekueSVzGjkHXZ3t02kTA//AdRMazjR4oLn2qUQyza6UpJ0nYictuq3arIohElSkg4KPD4Pu0t1raoo6AAL9Q3lee7IVvgfUsmkwdHbeoqf97oQhdcOGMUryo5B+Y2QnJtyK9M+dZ5UFThhd2YyVKZ/yktRia7AVSNR3Mm5NKkaebxN/fv6S/h/x3clc6ndDOBM6LLHOFaBKTDiejWiV7BnRDQcscUXTZtMkmZ58ogSi8ZScbwGPm6mLG3OjVC6CCLbDgFFk1GNM3eO0mpt6lmDV+Wq5vdZOSjDYE4rRnZ2KcAzzm9+C2DAypGWde4FCLKJo0U6yTRsxEjOK5lHVdQdU9V6O3A+Ll34iDmTQ38felaKQdJSOgWr6/H96zQ9Q39tUPjw1FRtf8W4=
  on:
    tags: true
  gem: logstash-filter-cache-redis
